from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path


# Result families that existed before the 2026-08-09 repair work. Tests that
# exercise whole-tree analysis build their input from this fixed list rather
# than from a live scan of results/raw: the sensitivity report emits a coverage
# row only when a stratum is *missing*, so simply adding a new benchmark run to
# the repository could delete an expected line and fail an unrelated test. That
# happened once, when a sweep introduced the first rows reporting divergences.
_FIXTURE_FAMILIES = (
    "funnel_ablation",
    "chain_scaling",
    "dimension_scaling",
    "eight_schools",
    "gp",
    "hier_logistic",
    "stoch_vol",
    "long_trace",
    "trace_qa",
)


def _build_raw_fixture(repo_root: Path, destination: Path) -> Path:
    """Copy a fixed subset of raw results so whole-tree tests are deterministic."""
    source_root = repo_root / "results" / "raw"
    destination.mkdir(parents=True, exist_ok=True)
    for family in _FIXTURE_FAMILIES:
        family_dir = source_root / family
        if family_dir.is_dir():
            shutil.copytree(family_dir, destination / family, dirs_exist_ok=True)
    return destination


def test_report_generates_latex_outputs_from_tiny_ablation(tmp_path: Path) -> None:
    repo_root = Path(__file__).resolve().parents[1]
    out_dir = tmp_path / "latex"

    env = os.environ.copy()
    src_path = str(repo_root / "src")
    env["PYTHONPATH"] = src_path + os.pathsep + env.get("PYTHONPATH", "")

    completed = subprocess.run(
        [
            sys.executable,
            "-m",
            "abnuts.analysis.report",
            "--input",
            str(repo_root / "results" / "raw" / "funnel_ablation" / "tiny"),
            "--out",
            str(out_dir),
        ],
        check=True,
        cwd=repo_root,
        env=env,
        text=True,
        capture_output=True,
    )

    table = out_dir / "tables" / "table_bucket_ablation.tex"
    figure = out_dir / "figures" / "fig_speedup_vs_bucket_size.tex"
    macros = out_dir / "macros" / "result_macros.tex"

    assert table.exists()
    assert figure.exists()
    assert macros.exists()
    assert "Wrote LaTeX table" in completed.stdout

    table_text = table.read_text(encoding="utf-8")
    figure_text = figure.read_text(encoding="utf-8")
    macros_text = macros.read_text(encoding="utf-8")

    assert "% Generated by: python -m abnuts.analysis.report" in table_text
    assert "% Source result file:" in table_text
    assert "\\begin{table}" in table_text
    assert "\\begin{tabular}" in table_text
    assert "history" in table_text

    assert "% Source result file:" in figure_text
    assert "\\begin{tikzpicture}" in figure_text
    assert "\\begin{axis}" in figure_text
    assert "\\addplot+" in figure_text

    assert "% Source result file:" in macros_text
    assert "\\newcommand{\\BestWarmSpeedup}" in macros_text
    assert "\\newcommand{\\BestWarmSpeedupConfig}" in macros_text


def test_report_generates_scheduler_interpretability_outputs(tmp_path: Path) -> None:
    repo_root = Path(__file__).resolve().parents[1]
    out_dir = tmp_path / "latex"

    env = os.environ.copy()
    src_path = str(repo_root / "src")
    env["PYTHONPATH"] = src_path + os.pathsep + env.get("PYTHONPATH", "")

    completed = subprocess.run(
        [
            sys.executable,
            "-m",
            "abnuts.analysis.report",
            "--input",
            str(repo_root / "results" / "raw" / "oracle_gap" / "tiny"),
            "--out",
            str(out_dir),
        ],
        check=True,
        cwd=repo_root,
        env=env,
        text=True,
        capture_output=True,
    )

    figures_dir = out_dir / "figures"
    expected_figures = [
        figures_dir / "fig_oracle_gap_waterfall.tex",
        figures_dir / "fig_predictor_calibration.tex",
        figures_dir / "fig_padding_heatmap.tex",
        figures_dir / "fig_speedup_vs_heterogeneity.tex",
    ]
    expected_sources = [
        figures_dir / "predictor_calibration.csv",
        figures_dir / "padding_heatmap.csv",
        figures_dir / "speedup_vs_heterogeneity.csv",
    ]

    assert "Wrote LaTeX figure" in completed.stdout
    assert (out_dir / "tables" / "table_oracle_gap.tex").exists()
    for path in expected_figures + expected_sources:
        assert path.exists()

    for figure in expected_figures:
        text = figure.read_text(encoding="utf-8")
        assert "% Source result file:" in text
        assert "\\begin{tikzpicture}" in text
        assert "\\begin{axis}" in text
        assert "analysis-only" in text

    for source in expected_sources:
        rows = source.read_text(encoding="utf-8").strip().splitlines()
        assert len(rows) > 1


def test_report_generates_sensitivity_outputs_from_raw_tree(tmp_path: Path) -> None:
    repo_root = Path(__file__).resolve().parents[1]
    out_dir = tmp_path / "latex"

    env = os.environ.copy()
    src_path = str(repo_root / "src")
    env["PYTHONPATH"] = src_path + os.pathsep + env.get("PYTHONPATH", "")

    completed = subprocess.run(
        [
            sys.executable,
            "-m",
            "abnuts.analysis.report",
            "--input",
            str(_build_raw_fixture(repo_root, tmp_path / "raw_fixture")),
            "--out",
            str(out_dir),
            "--include-sensitivity",
        ],
        check=True,
        cwd=repo_root,
        env=env,
        text=True,
        capture_output=True,
    )

    worst_table = out_dir / "tables" / "table_sensitivity_worst_groups.tex"
    coverage_table = out_dir / "tables" / "table_sensitivity_coverage.tex"
    summary = out_dir / "sensitivity_summary.tex"

    assert worst_table.exists()
    assert coverage_table.exists()
    assert summary.exists()
    assert "Wrote LaTeX summary" in completed.stdout

    worst_text = worst_table.read_text(encoding="utf-8")
    coverage_text = coverage_table.read_text(encoding="utf-8")
    summary_text = summary.read_text(encoding="utf-8")

    assert "Smoke-only evidence" in worst_text
    assert "model family" in worst_text
    assert "predictor mode" in worst_text
    assert "Missing strata are reported" in coverage_text
    assert "divergence status" in coverage_text
    assert "Smoke-only evidence" in summary_text
    assert "\\input{tables/table_sensitivity_worst_groups}" in summary_text


def test_report_generates_aggregate_bundle_from_raw_tree(tmp_path: Path) -> None:
    repo_root = Path(__file__).resolve().parents[1]
    out_dir = tmp_path / "latex" / "all"

    env = os.environ.copy()
    src_path = str(repo_root / "src")
    env["PYTHONPATH"] = src_path + os.pathsep + env.get("PYTHONPATH", "")

    completed = subprocess.run(
        [
            sys.executable,
            "-m",
            "abnuts.analysis.report",
            "--input",
            str(repo_root / "results" / "raw"),
            "--out",
            str(out_dir),
            "--allow-missing",
        ],
        check=True,
        cwd=repo_root,
        env=env,
        text=True,
        capture_output=True,
    )

    processed_dir = tmp_path / "processed" / "all"
    summary = out_dir / "results_summary.tex"
    manifest = out_dir / "manifest.json"

    expected_latex = [
        out_dir / "tables" / "table_bucket_ablation.tex",
        out_dir / "tables" / "table_chain_scaling.tex",
        out_dir / "tables" / "table_dimension_scaling.tex",
        out_dir / "tables" / "table_oracle_gap.tex",
        out_dir / "tables" / "table_diagnostics.tex",
        out_dir / "tables" / "table_runtime_breakdown.tex",
        out_dir / "figures" / "fig_speedup_vs_bucket_size.tex",
        out_dir / "figures" / "fig_chain_scaling.tex",
        out_dir / "figures" / "fig_dimension_scaling.tex",
        out_dir / "figures" / "fig_oracle_gap_waterfall.tex",
        out_dir / "figures" / "fig_predictor_calibration.tex",
        out_dir / "figures" / "fig_padding_heatmap.tex",
        out_dir / "figures" / "fig_speedup_vs_heterogeneity.tex",
        out_dir / "figures" / "fig_runtime_breakdown.tex",
        out_dir / "figures" / "fig_sbc_rank_histogram.tex",
        out_dir / "macros" / "result_macros.tex",
        summary,
    ]
    for path in expected_latex:
        assert path.exists(), path

    assert manifest.exists()
    assert (processed_dir / "all_summary.csv").exists()
    assert (processed_dir / "equivalence_checks.csv").exists()
    assert (processed_dir / "missing_results.csv").exists()

    summary_text = summary.read_text(encoding="utf-8")
    macros_text = (out_dir / "macros" / "result_macros.tex").read_text(encoding="utf-8")
    manifest_text = manifest.read_text(encoding="utf-8")

    assert "TODO\\_RESULT" in summary_text
    assert "\\input{tables/table_bucket_ablation}" in summary_text
    assert "\\input{figures/fig_oracle_gap_waterfall}" in summary_text
    assert "analysis-only upper bounds" in summary_text
    assert "\\newcommand{\\PaperScaleEvidenceStatus}{TODO_RESULT}" in macros_text
    assert "table_bucket_ablation.tex" in manifest_text
    assert "Wrote report manifest" in completed.stdout
