"""PGFPlots figure generation for benchmark summaries."""

from __future__ import annotations

import csv
from pathlib import Path

from abnuts.analysis.aggregate import (
    AblationSummary,
    ChainScalingSummary,
    DimensionScalingSummary,
    OracleGapSummary,
    PaddingHeatmapSummary,
    PredictorCalibrationSummary,
    RuntimeBreakdownSummary,
    SBCRankHistogramSummary,
    SpeedupHeterogeneitySummary,
)


def write_speedup_vs_bucket_size_figure(
    summary: AblationSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write a PGFPlots figure for speedup versus bucket size."""
    figure_dir = Path(out_dir) / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    figure_path = figure_dir / "fig_speedup_vs_bucket_size.tex"
    predictors = tuple(dict.fromkeys(row.predictor for row in summary.rows))
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        "  xlabel={Bucket size},",
        "  ylabel={Warm speedup},",
        "  legend pos=north west,",
        "  grid=both,",
        "  width=0.78\\linewidth,",
        "  height=0.48\\linewidth,",
        "]",
    ]
    for predictor in predictors:
        coords = " ".join(
            f"({row.bucket_size},{row.mean_speedup:.6f})"
            for row in summary.rows
            if row.predictor == predictor
        )
        lines.extend(
            [
                f"\\addplot+[mark=*] coordinates {{{coords}}};",
                f"\\addlegendentry{{{_escape_latex(predictor)}}}",
            ]
        )
    lines.extend(
        [
            "\\end{axis}",
            "\\end{tikzpicture}",
            "",
        ]
    )
    figure_path.write_text("\n".join(lines), encoding="utf-8")
    return figure_path


def write_chain_scaling_figure(
    summary: ChainScalingSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write a PGFPlots figure for speedup versus chain count."""
    figure_dir = Path(out_dir) / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    figure_path = figure_dir / "fig_chain_scaling.tex"
    series = tuple(dict.fromkeys((row.predictor, row.bucket_size) for row in summary.rows))
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        "  xlabel={Chains},",
        "  ylabel={Warm speedup},",
        "  legend pos=north west,",
        "  grid=both,",
        "  width=0.78\\linewidth,",
        "  height=0.48\\linewidth,",
        "]",
    ]
    for predictor, bucket_size in series:
        coords = " ".join(
            f"({row.num_chains},{row.mean_speedup:.6f})"
            for row in summary.rows
            if row.predictor == predictor and row.bucket_size == bucket_size
        )
        lines.extend(
            [
                f"\\addplot+[mark=*] coordinates {{{coords}}};",
                f"\\addlegendentry{{{_escape_latex(predictor)}, S={bucket_size}}}",
            ]
        )
    lines.extend(
        [
            "\\end{axis}",
            "\\end{tikzpicture}",
            "",
        ]
    )
    figure_path.write_text("\n".join(lines), encoding="utf-8")
    return figure_path


def write_dimension_scaling_figure(
    summary: DimensionScalingSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write a PGFPlots figure for speedup versus model dimension."""
    figure_dir = Path(out_dir) / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    figure_path = figure_dir / "fig_dimension_scaling.tex"
    series = tuple(dict.fromkeys((row.predictor, row.bucket_size) for row in summary.rows))
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        "  xlabel={Dimension},",
        "  ylabel={Warm speedup},",
        "  legend pos=north west,",
        "  grid=both,",
        "  width=0.78\\linewidth,",
        "  height=0.48\\linewidth,",
        "]",
    ]
    for predictor, bucket_size in series:
        coords = " ".join(
            f"({row.dimension},{row.mean_speedup:.6f})"
            for row in summary.rows
            if row.predictor == predictor and row.bucket_size == bucket_size
        )
        lines.extend(
            [
                f"\\addplot+[mark=*] coordinates {{{coords}}};",
                f"\\addlegendentry{{{_escape_latex(predictor)}, S={bucket_size}}}",
            ]
        )
    lines.extend(
        [
            "\\end{axis}",
            "\\end{tikzpicture}",
            "",
        ]
    )
    figure_path.write_text("\n".join(lines), encoding="utf-8")
    return figure_path


def write_oracle_gap_waterfall_figure(
    summary: OracleGapSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write a PGFPlots bar figure for oracle-gap scheduler speedups."""
    figure_dir = Path(out_dir) / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    figure_path = figure_dir / "fig_oracle_gap_waterfall.tex"
    xticklabels = ", ".join(
        _escape_latex(_short_oracle_gap_label(row.scheduler_label, row.bucket_size))
        for row in summary.rows
    )
    coords = " ".join(
        f"({index + 1},{row.mean_speedup:.6f})" for index, row in enumerate(summary.rows)
    )
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        "% oracle_current is an analysis-only upper bound, not a deployable scheduler.",
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        "  ybar,",
        "  xlabel={Scheduler},",
        "  ylabel={Warm speedup},",
        "  ymin=0,",
        "  grid=both,",
        "  width=0.88\\linewidth,",
        "  height=0.50\\linewidth,",
        f"  xtick={{{', '.join(str(index + 1) for index, _ in enumerate(summary.rows))}}},",
        f"  xticklabels={{{xticklabels}}},",
        "  x tick label style={rotate=35, anchor=east},",
        "  title={Oracle-current is an analysis-only upper bound},",
        "]",
        f"\\addplot+[fill=gray!35] coordinates {{{coords}}};",
        "\\end{axis}",
        "\\end{tikzpicture}",
        "",
    ]
    figure_path.write_text("\n".join(lines), encoding="utf-8")
    return figure_path


def write_predictor_calibration_figure(
    summary: PredictorCalibrationSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write a PGFPlots predictor calibration scatter figure."""
    figure_dir = Path(out_dir) / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    source_path = figure_dir / "predictor_calibration.csv"
    figure_path = figure_dir / "fig_predictor_calibration.tex"
    _write_predictor_calibration_csv(summary, source_path)

    series = tuple(dict.fromkeys(row.scheduler_label for row in summary.rows))
    max_axis_value = max(
        (max(row.predicted_work, row.realized_work) for row in summary.rows),
        default=1.0,
    )
    identity_max = max(1.0, max_axis_value)
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        f"% Source figure data: {source_path.name}",
        "% oracle_current is an analysis-only upper bound, not a deployable scheduler.",
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        "  xlabel={Predicted work},",
        "  ylabel={Realized tree depth},",
        "  legend pos=north west,",
        "  grid=both,",
        "  width=0.78\\linewidth,",
        "  height=0.52\\linewidth,",
        "  title={Predictor calibration; oracle-current is analysis-only},",
        "]",
        "\\addplot+[gray, dashed, mark=none] coordinates "
        f"{{(0,0) ({identity_max:.6f},{identity_max:.6f})}};",
        "\\addlegendentry{ideal}",
    ]
    for label in series:
        coords = " ".join(
            f"({row.predicted_work:.6f},{row.realized_work:.6f})"
            for row in summary.rows
            if row.scheduler_label == label
        )
        if not coords:
            continue
        lines.extend(
            [
                f"\\addplot+[only marks] coordinates {{{coords}}};",
                f"\\addlegendentry{{{_escape_latex(_short_oracle_gap_label(label, 0))}}}",
            ]
        )
    lines.extend(["\\end{axis}", "\\end{tikzpicture}", ""])
    figure_path.write_text("\n".join(lines), encoding="utf-8")
    return figure_path


def write_padding_heatmap_figure(
    summary: PaddingHeatmapSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write a PGFPlots padding and occupancy heatmap figure."""
    figure_dir = Path(out_dir) / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    source_path = figure_dir / "padding_heatmap.csv"
    figure_path = figure_dir / "fig_padding_heatmap.tex"
    _write_padding_heatmap_csv(summary, source_path)

    coords = " ".join(
        f"({row.step},{row.bucket_index}) [{row.fill_fraction:.6f}]"
        for row in summary.rows
    )
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        f"% Source figure data: {source_path.name}",
        "% oracle_current is an analysis-only upper bound, not a deployable scheduler.",
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        "  xlabel={Iteration},",
        "  ylabel={Bucket},",
        "  colorbar,",
        "  colormap/viridis,",
        "  point meta min=0,",
        "  point meta max=1,",
        "  grid=both,",
        "  width=0.78\\linewidth,",
        "  height=0.52\\linewidth,",
        "  title={Bucket fill fraction; oracle-current is analysis-only},",
        "]",
        "\\addplot+[",
        "  scatter,",
        "  only marks,",
        "  mark=square*,",
        "  mark size=6pt,",
        "  scatter src=explicit,",
        f"] coordinates {{{coords}}};",
        "\\end{axis}",
        "\\end{tikzpicture}",
        "",
    ]
    figure_path.write_text("\n".join(lines), encoding="utf-8")
    return figure_path


def write_speedup_vs_heterogeneity_figure(
    summary: SpeedupHeterogeneitySummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write a PGFPlots scatter figure for speedup versus work heterogeneity."""
    figure_dir = Path(out_dir) / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    source_path = figure_dir / "speedup_vs_heterogeneity.csv"
    figure_path = figure_dir / "fig_speedup_vs_heterogeneity.tex"
    _write_speedup_heterogeneity_csv(summary, source_path)

    series = tuple(dict.fromkeys(row.scheduler_label for row in summary.rows))
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        f"% Source figure data: {source_path.name}",
        "% oracle_current is an analysis-only upper bound, not a deployable scheduler.",
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        "  xlabel={Realized-depth heterogeneity},",
        "  ylabel={Warm speedup},",
        "  legend pos=north west,",
        "  grid=both,",
        "  width=0.78\\linewidth,",
        "  height=0.52\\linewidth,",
        "  title={Speedup versus heterogeneity; oracle-current is analysis-only},",
        "]",
    ]
    for label in series:
        coords = " ".join(
            f"({row.heterogeneity:.6f},{row.speedup:.6f})"
            for row in summary.rows
            if row.scheduler_label == label
        )
        if not coords:
            continue
        lines.extend(
            [
                f"\\addplot+[only marks] coordinates {{{coords}}};",
                f"\\addlegendentry{{{_escape_latex(_short_oracle_gap_label(label, 0))}}}",
            ]
        )
    lines.extend(["\\end{axis}", "\\end{tikzpicture}", ""])
    figure_path.write_text("\n".join(lines), encoding="utf-8")
    return figure_path


def write_runtime_breakdown_figure(
    summary: RuntimeBreakdownSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write a stacked PGFPlots runtime component figure."""
    figure_dir = Path(out_dir) / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    source_path = figure_dir / "runtime_breakdown.csv"
    figure_path = figure_dir / "fig_runtime_breakdown.tex"
    _write_runtime_breakdown_csv(summary, source_path)

    labels = ", ".join(
        _escape_latex(_runtime_breakdown_label(row.method, row.predictor, row.bucket_size))
        for row in summary.rows
    )
    xticks = ", ".join(str(index + 1) for index, _row in enumerate(summary.rows))
    components = (
        ("Cold compile", "mean_cold_compile_seconds"),
        ("Planner", "mean_planner_seconds"),
        ("Executor", "mean_executor_seconds"),
        ("Gather", "mean_gather_seconds"),
        ("Scatter", "mean_scatter_seconds"),
        ("HVP", "mean_hvp_seconds"),
        ("Other warm", "mean_unattributed_seconds"),
    )
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        f"% Source figure data: {source_path.name}",
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        "  ybar stacked,",
        "  xlabel={Run configuration},",
        "  ylabel={Seconds},",
        "  legend columns=2,",
        "  legend pos=north west,",
        "  grid=both,",
        "  width=0.88\\linewidth,",
        "  height=0.54\\linewidth,",
        f"  xtick={{{xticks}}},",
        f"  xticklabels={{{labels}}},",
        "  x tick label style={rotate=35, anchor=east},",
        "]",
    ]
    for label, attribute in components:
        coords = " ".join(
            f"({index + 1},{getattr(row, attribute):.6f})"
            for index, row in enumerate(summary.rows)
        )
        lines.extend(
            [
                f"\\addplot+ coordinates {{{coords}}};",
                f"\\addlegendentry{{{_escape_latex(label)}}}",
            ]
        )
    lines.extend(["\\end{axis}", "\\end{tikzpicture}", ""])
    figure_path.write_text("\n".join(lines), encoding="utf-8")
    return figure_path


def write_sbc_rank_histogram_figure(
    summary: SBCRankHistogramSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write a PGFPlots SBC rank histogram figure."""
    figure_dir = Path(out_dir) / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    source_path = figure_dir / "sbc_rank_histogram.csv"
    figure_path = figure_dir / "fig_sbc_rank_histogram.tex"
    _write_sbc_rank_histogram_csv(summary, source_path)

    methods = tuple(dict.fromkeys(row.method for row in summary.rows))
    ranks = sorted({row.rank for row in summary.rows})
    xticks = ", ".join(str(rank) for rank in ranks)
    title = (
        "Tiny SBC smoke only; not paper evidence"
        if summary.is_smoke_only
        else "Simulation-based calibration ranks"
    )
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        f"% Source figure data: {source_path.name}",
    ]
    if summary.is_smoke_only:
        lines.append("% Tiny SBC profile is smoke-only and not paper evidence.")
    lines.extend(
        [
            "\\begin{tikzpicture}",
            "\\begin{axis}[",
            "  ybar,",
            "  xlabel={Rank},",
            "  ylabel={Replicates},",
            "  legend pos=north east,",
            "  grid=both,",
            "  width=0.78\\linewidth,",
            "  height=0.50\\linewidth,",
            f"  xtick={{{xticks}}},",
            f"  title={{{_escape_latex(title)}}},",
            "]",
        ]
    )
    for method in methods:
        coords = " ".join(
            f"({row.rank},{row.count})" for row in summary.rows if row.method == method
        )
        lines.extend(
            [
                f"\\addplot+ coordinates {{{coords}}};",
                f"\\addlegendentry{{{_escape_latex(method)}}}",
            ]
        )
    lines.extend(["\\end{axis}", "\\end{tikzpicture}", ""])
    figure_path.write_text("\n".join(lines), encoding="utf-8")
    return figure_path


def _write_predictor_calibration_csv(
    summary: PredictorCalibrationSummary,
    source_path: Path,
) -> None:
    with source_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "scheduler_mode",
                "scheduler_label",
                "bucket_size",
                "is_analysis_upper_bound",
                "predicted_work",
                "realized_work",
                "abs_error",
                "is_summary_proxy",
            ],
            lineterminator="\n",
        )
        writer.writeheader()
        for row in summary.rows:
            writer.writerow(
                {
                    "scheduler_mode": row.scheduler_mode,
                    "scheduler_label": row.scheduler_label,
                    "bucket_size": row.bucket_size,
                    "is_analysis_upper_bound": row.is_analysis_upper_bound,
                    "predicted_work": f"{row.predicted_work:.8g}",
                    "realized_work": f"{row.realized_work:.8g}",
                    "abs_error": f"{row.abs_error:.8g}",
                    "is_summary_proxy": row.is_summary_proxy,
                }
            )


def _write_sbc_rank_histogram_csv(
    summary: SBCRankHistogramSummary,
    source_path: Path,
) -> None:
    with source_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "method",
                "rank",
                "count",
                "num_replicates",
                "num_posterior_samples",
                "is_smoke_only",
                "evidence_note",
            ],
            lineterminator="\n",
        )
        writer.writeheader()
        for row in summary.rows:
            writer.writerow(
                {
                    "method": row.method,
                    "rank": row.rank,
                    "count": row.count,
                    "num_replicates": row.num_replicates,
                    "num_posterior_samples": row.num_posterior_samples,
                    "is_smoke_only": row.is_smoke_only,
                    "evidence_note": row.evidence_note,
                }
            )


def _write_runtime_breakdown_csv(
    summary: RuntimeBreakdownSummary,
    source_path: Path,
) -> None:
    with source_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "method",
                "predictor",
                "bucket_size",
                "runs",
                "mean_cold_run_seconds",
                "mean_cold_compile_seconds",
                "mean_warm_iteration_seconds",
                "mean_planner_seconds",
                "mean_executor_seconds",
                "mean_gather_seconds",
                "mean_scatter_seconds",
                "mean_hvp_seconds",
                "mean_unattributed_seconds",
                "mean_profiler_marker_count",
            ],
            lineterminator="\n",
        )
        writer.writeheader()
        for row in summary.rows:
            writer.writerow(
                {
                    "method": row.method,
                    "predictor": row.predictor,
                    "bucket_size": row.bucket_size,
                    "runs": row.runs,
                    "mean_cold_run_seconds": f"{row.mean_cold_run_seconds:.8g}",
                    "mean_cold_compile_seconds": f"{row.mean_cold_compile_seconds:.8g}",
                    "mean_warm_iteration_seconds": f"{row.mean_warm_iteration_seconds:.8g}",
                    "mean_planner_seconds": f"{row.mean_planner_seconds:.8g}",
                    "mean_executor_seconds": f"{row.mean_executor_seconds:.8g}",
                    "mean_gather_seconds": f"{row.mean_gather_seconds:.8g}",
                    "mean_scatter_seconds": f"{row.mean_scatter_seconds:.8g}",
                    "mean_hvp_seconds": f"{row.mean_hvp_seconds:.8g}",
                    "mean_unattributed_seconds": f"{row.mean_unattributed_seconds:.8g}",
                    "mean_profiler_marker_count": f"{row.mean_profiler_marker_count:.8g}",
                }
            )


def _write_padding_heatmap_csv(summary: PaddingHeatmapSummary, source_path: Path) -> None:
    with source_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "scheduler_mode",
                "scheduler_label",
                "bucket_size",
                "is_analysis_upper_bound",
                "step",
                "bucket_index",
                "padding_count",
                "fill_fraction",
                "bucket_realized_max",
            ],
            lineterminator="\n",
        )
        writer.writeheader()
        for row in summary.rows:
            writer.writerow(
                {
                    "scheduler_mode": row.scheduler_mode,
                    "scheduler_label": row.scheduler_label,
                    "bucket_size": row.bucket_size,
                    "is_analysis_upper_bound": row.is_analysis_upper_bound,
                    "step": row.step,
                    "bucket_index": row.bucket_index,
                    "padding_count": row.padding_count,
                    "fill_fraction": f"{row.fill_fraction:.8g}",
                    "bucket_realized_max": f"{row.bucket_realized_max:.8g}",
                }
            )


def _write_speedup_heterogeneity_csv(
    summary: SpeedupHeterogeneitySummary,
    source_path: Path,
) -> None:
    with source_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "scheduler_mode",
                "scheduler_label",
                "bucket_size",
                "is_analysis_upper_bound",
                "speedup",
                "heterogeneity",
            ],
            lineterminator="\n",
        )
        writer.writeheader()
        for row in summary.rows:
            writer.writerow(
                {
                    "scheduler_mode": row.scheduler_mode,
                    "scheduler_label": row.scheduler_label,
                    "bucket_size": row.bucket_size,
                    "is_analysis_upper_bound": row.is_analysis_upper_bound,
                    "speedup": f"{row.speedup:.8g}",
                    "heterogeneity": f"{row.heterogeneity:.8g}",
                }
            )


def _escape_latex(value: str) -> str:
    return (
        value.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("$", "\\$")
        .replace("#", "\\#")
        .replace("_", "\\_")
        .replace("{", "\\{")
        .replace("}", "\\}")
    )


def _short_oracle_gap_label(scheduler_label: str, bucket_size: int) -> str:
    label = scheduler_label.replace(" (analysis-only upper bound)", " upper")
    if bucket_size == 0:
        return label
    return f"{label} S={bucket_size}"


def _runtime_breakdown_label(method: str, predictor: str, bucket_size: int) -> str:
    if method == "bucketed":
        return f"{predictor} S={bucket_size}"
    return method
