"""LaTeX table generation for benchmark summaries."""

from __future__ import annotations

from pathlib import Path

from abnuts.analysis.aggregate import (
    AblationRow,
    AblationSummary,
    ChainScalingRow,
    ChainScalingSummary,
    DiagnosticsSummary,
    DimensionScalingRow,
    DimensionScalingSummary,
    OracleGapSummary,
    RuntimeBreakdownSummary,
)
from abnuts.analysis.sensitivity import SensitivitySummary


def write_bucket_ablation_table(
    summary: AblationSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write the funnel bucket-ablation table as LaTeX source."""
    table_dir = Path(out_dir) / "tables"
    table_dir.mkdir(parents=True, exist_ok=True)
    table_path = table_dir / "table_bucket_ablation.tex"
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Funnel bucket-size and predictor ablation.}",
        "\\label{tab:bucket-ablation}",
        "\\begin{tabular}{lrrrrrr}",
        "\\hline",
        "Predictor & Bucket & Runs & $t_{\\mathrm{mono}}$ & "
        "$t_{\\mathrm{bucket}}$ & Speedup & Padding \\\\",
        "\\hline",
    ]
    for row in summary.rows:
        lines.append(
            f"{_escape_latex(row.predictor)} & {row.bucket_size} & {row.runs} & "
            f"{row.mean_t_mono:.4f} & {row.mean_t_bucket:.4f} & "
            f"{row.mean_speedup:.3f} & {row.mean_padding_ratio:.3f} \\\\"
        )
    lines.extend(
        [
            "\\hline",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    table_path.write_text("\n".join(lines), encoding="utf-8")
    return table_path


def write_result_macros(
    summary: AblationSummary | ChainScalingSummary | DimensionScalingSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write reusable LaTeX macros for a benchmark summary."""
    macros_dir = Path(out_dir) / "macros"
    macros_dir.mkdir(parents=True, exist_ok=True)
    macros_path = macros_dir / "result_macros.tex"
    best = summary.best_row
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        f"\\newcommand{{\\BestWarmSpeedup}}{{{best.mean_speedup:.3f}}}",
        f"\\newcommand{{\\BestWarmSpeedupConfig}}{{{_best_config_text(best)}}}",
    ]
    if isinstance(summary, AblationSummary):
        lines.append(
            f"\\newcommand{{\\FunnelHistorySpeedupCtiny}}{{{_history_speedup(summary):.3f}}}"
        )
    if isinstance(summary, ChainScalingSummary):
        lines.append(
            f"\\newcommand{{\\ChainScalingBestChains}}{{{summary.best_row.num_chains}}}"
        )
        lines.append(
            f"\\newcommand{{\\ChainScalingBestSpeedup}}{{{summary.best_row.mean_speedup:.3f}}}"
        )
    if isinstance(summary, DimensionScalingSummary):
        lines.append(
            f"\\newcommand{{\\DimensionScalingBestDimension}}{{{summary.best_row.dimension}}}"
        )
        lines.append(
            "\\newcommand{\\DimensionScalingBestSpeedup}"
            f"{{{summary.best_row.mean_speedup:.3f}}}"
        )
    lines.append("")
    macros_path.write_text("\n".join(lines), encoding="utf-8")
    return macros_path


def write_chain_scaling_table(
    summary: ChainScalingSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write the chain-scaling table as LaTeX source."""
    table_dir = Path(out_dir) / "tables"
    table_dir.mkdir(parents=True, exist_ok=True)
    table_path = table_dir / "table_chain_scaling.tex"
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Funnel chain-scaling benchmark.}",
        "\\label{tab:chain-scaling}",
        "\\begin{tabular}{rlrrrrr}",
        "\\hline",
        "Chains & Predictor & Bucket & Runs & $t_{\\mathrm{mono}}$ & "
        "$t_{\\mathrm{bucket}}$ & Speedup \\\\",
        "\\hline",
    ]
    for row in summary.rows:
        lines.append(
            f"{row.num_chains} & {_escape_latex(row.predictor)} & {row.bucket_size} & "
            f"{row.runs} & {row.mean_t_mono:.4f} & {row.mean_t_bucket:.4f} & "
            f"{row.mean_speedup:.3f} \\\\"
        )
    lines.extend(
        [
            "\\hline",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    table_path.write_text("\n".join(lines), encoding="utf-8")
    return table_path


def write_dimension_scaling_table(
    summary: DimensionScalingSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write the dimension-scaling table as LaTeX source."""
    table_dir = Path(out_dir) / "tables"
    table_dir.mkdir(parents=True, exist_ok=True)
    table_path = table_dir / "table_dimension_scaling.tex"
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Funnel dimension-scaling benchmark.}",
        "\\label{tab:dimension-scaling}",
        "\\begin{tabular}{rlrrrrr}",
        "\\hline",
        "Dimension & Predictor & Bucket & Runs & $t_{\\mathrm{mono}}$ & "
        "$t_{\\mathrm{bucket}}$ & Speedup \\\\",
        "\\hline",
    ]
    for row in summary.rows:
        lines.append(
            f"{row.dimension} & {_escape_latex(row.predictor)} & {row.bucket_size} & "
            f"{row.runs} & {row.mean_t_mono:.4f} & {row.mean_t_bucket:.4f} & "
            f"{row.mean_speedup:.3f} \\\\"
        )
    lines.extend(
        [
            "\\hline",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    table_path.write_text("\n".join(lines), encoding="utf-8")
    return table_path


def write_diagnostics_table(
    summary: DiagnosticsSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write a LaTeX table for tiny trace-level diagnostics."""
    table_dir = Path(out_dir) / "tables"
    table_dir.mkdir(parents=True, exist_ok=True)
    table_path = table_dir / "table_diagnostics.tex"
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Tiny trace-level posterior diagnostics.}",
        "\\label{tab:diagnostics}",
        "\\begin{tabular}{llrrrrrrr}",
        "\\hline",
        "Method & Variable & Mean & SD & $\\widehat{R}$ & Bulk ESS & "
        "Tail ESS & MCSE & Div. \\\\",
        "\\hline",
    ]
    for row in summary.rows:
        lines.append(
            f"{_escape_latex(row.method)} & {_escape_latex(row.variable)} & "
            f"{_format_float(row.mean, 3)} & {_format_float(row.sd, 3)} & "
            f"{_format_float(row.r_hat, 3)} & {_format_float(row.bulk_ess, 1)} & "
            f"{_format_float(row.tail_ess, 1)} & {_format_float(row.mcse_mean, 3)} & "
            f"{row.divergence_count} \\\\"
        )
    lines.extend(
        [
            "\\hline",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    table_path.write_text("\n".join(lines), encoding="utf-8")
    return table_path


def write_oracle_gap_table(
    summary: OracleGapSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write the oracle-gap decomposition table as LaTeX source."""
    table_dir = Path(out_dir) / "tables"
    table_dir.mkdir(parents=True, exist_ok=True)
    table_path = table_dir / "table_oracle_gap.tex"
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        "% oracle_current is an analysis-only upper bound, not a deployable scheduler.",
        "\\begin{table}[t]",
        "\\centering",
        "\\scriptsize",
        "\\caption{Oracle-gap scheduler decomposition. "
        "Oracle-current is an analysis-only upper bound, not a deployable scheduler.}",
        "\\label{tab:oracle-gap}",
        "\\begin{tabular}{lrrrrrrrrrrrl}",
        "\\hline",
        "Scheduler & Bucket & Runs & Speedup & Padding & Pred. MAE & "
        "Cold comp. & Warm & Planner & Executor & G+S & Other & Dominant \\\\",
        "\\hline",
    ]
    for row in summary.rows:
        lines.append(
            f"{_escape_latex(row.scheduler_label)} & {_format_bucket_size(row.bucket_size)} & "
            f"{row.runs} & {row.mean_speedup:.3f} & "
            f"{row.mean_padding_ratio:.3f} & {row.mean_predictor_abs_error:.3f} & "
            f"{row.mean_cold_compile_seconds:.4f} & "
            f"{row.mean_warm_iteration_seconds:.4f} & "
            f"{row.mean_planner_seconds:.4f} & "
            f"{row.mean_executor_seconds:.4f} & "
            f"{row.mean_gather_scatter_seconds:.4f} & "
            f"{row.mean_unattributed_seconds:.4f} & "
            f"{_escape_latex(row.dominant_warm_component)} \\\\"
        )
    lines.extend(
        [
            "\\hline",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    table_path.write_text("\n".join(lines), encoding="utf-8")
    return table_path


def write_runtime_breakdown_table(
    summary: RuntimeBreakdownSummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write a LaTeX table for profiling runtime components."""
    table_dir = Path(out_dir) / "tables"
    table_dir.mkdir(parents=True, exist_ok=True)
    table_path = table_dir / "table_runtime_breakdown.tex"
    lines = [
        f"% Generated by: {command}",
        f"% Source result file: {summary.source_csv}",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Runtime breakdown for profiled tiny benchmark runs. "
        "Cold compile is estimated as cold-run minus warm-run time.}",
        "\\label{tab:runtime-breakdown}",
        "\\begin{tabular}{llrrrrrrrrrr}",
        "\\hline",
        "Method & Predictor & Bucket & Runs & Cold comp. & Warm & Planner & "
        "Executor & Gather & Scatter & HVP & Other \\\\",
        "\\hline",
    ]
    for row in summary.rows:
        lines.append(
            f"{_escape_latex(row.method)} & {_escape_latex(row.predictor)} & "
            f"{_format_bucket_size(row.bucket_size)} & {row.runs} & "
            f"{row.mean_cold_compile_seconds:.4f} & "
            f"{row.mean_warm_iteration_seconds:.4f} & "
            f"{row.mean_planner_seconds:.4f} & "
            f"{row.mean_executor_seconds:.4f} & "
            f"{row.mean_gather_seconds:.4f} & "
            f"{row.mean_scatter_seconds:.4f} & "
            f"{row.mean_hvp_seconds:.4f} & "
            f"{row.mean_unattributed_seconds:.4f} \\\\"
        )
    lines.extend(
        [
            "\\hline",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    table_path.write_text("\n".join(lines), encoding="utf-8")
    return table_path


def write_sensitivity_worst_group_table(
    summary: SensitivitySummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write the sensitivity worst-group table as LaTeX source."""
    table_dir = Path(out_dir) / "tables"
    table_dir.mkdir(parents=True, exist_ok=True)
    table_path = table_dir / "table_sensitivity_worst_groups.tex"
    evidence = "Smoke-only evidence; not paper-scale claims." if summary.is_smoke_only else (
        "Paper-scale candidate evidence; check uncertainty before claiming."
    )
    lines = [
        f"% Generated by: {command}",
        f"% Source result root: {summary.source_root}",
        f"% {summary.evidence_note}",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Sensitivity worst-group report. " + _escape_latex(evidence) + "}",
        "\\label{tab:sensitivity-worst-groups}",
        "\\begin{tabular}{llrrrrrrr}",
        "\\hline",
        "Stratum & Worst group & Sources & Runs & Mean speedup & Worst speedup & "
        "Padding & Div. & Max depth \\\\",
        "\\hline",
    ]
    for row in summary.rows:
        group = row.group
        if row.analysis_upper_bound_runs:
            group = f"{group} ({row.analysis_upper_bound_runs} upper-bound rows)"
        lines.append(
            f"{_escape_latex(row.stratum)} & {_escape_latex(group)} & "
            f"{row.source_count} & {row.runs} & {row.mean_speedup:.3f} & "
            f"{row.worst_speedup:.3f} & {row.mean_padding_ratio:.3f} & "
            f"{row.total_divergences} & {row.max_tree_depth} \\\\"
        )
    lines.extend(
        [
            "\\hline",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    table_path.write_text("\n".join(lines), encoding="utf-8")
    return table_path


def write_sensitivity_coverage_table(
    summary: SensitivitySummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write coverage notes for missing or collapsed sensitivity strata."""
    table_dir = Path(out_dir) / "tables"
    table_dir.mkdir(parents=True, exist_ok=True)
    table_path = table_dir / "table_sensitivity_coverage.tex"
    lines = [
        f"% Generated by: {command}",
        f"% Source result root: {summary.source_root}",
        f"% {summary.evidence_note}",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Sensitivity coverage notes. Missing strata are reported here rather "
        "than silently dropped.}",
        "\\label{tab:sensitivity-coverage}",
        "\\begin{tabular}{lll}",
        "\\hline",
        "Requested stratum & Status & Note \\\\",
        "\\hline",
    ]
    for row in summary.coverage_rows:
        lines.append(
            f"{_escape_latex(row.stratum)} & {_escape_latex(row.status)} & "
            f"{_escape_latex(row.note)} \\\\"
        )
    lines.extend(
        [
            "\\hline",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )
    table_path.write_text("\n".join(lines), encoding="utf-8")
    return table_path


def write_sensitivity_summary(
    summary: SensitivitySummary,
    out_dir: str | Path,
    *,
    command: str,
) -> Path:
    """Write a short includeable LaTeX sensitivity summary."""
    out_path = Path(out_dir) / "sensitivity_summary.tex"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    worst = summary.worst_row
    lines = [
        f"% Generated by: {command}",
        f"% Source result root: {summary.source_root}",
        f"% {summary.evidence_note}",
        "\\paragraph{Sensitivity and worst-group evidence.}",
        _escape_latex(summary.evidence_note),
        "",
        (
            "The lowest observed worst-group mean speedup is "
            f"{worst.mean_speedup:.3f} for {_escape_latex(worst.stratum)} = "
            f"{_escape_latex(worst.group)} across {worst.runs} rows. "
            f"The worst single-row speedup in that group is {worst.worst_speedup:.3f}."
        ),
        "",
        (
            "Quality guardrails over included speedup rows report "
            f"{summary.total_divergences} total divergences and maximum realized tree depth "
            f"{summary.max_tree_depth}."
        ),
        "",
        (
            "Posterior-diagnostic coverage: "
            f"{summary.diagnostic_row_count} rows from {summary.diagnostic_file_count} "
            "diagnostics files; max $\\widehat{R}$ = "
            f"{_format_optional_float(summary.max_r_hat, 3)}, min bulk ESS = "
            f"{_format_optional_float(summary.min_bulk_ess, 1)}, min tail ESS = "
            f"{_format_optional_float(summary.min_tail_ess, 1)}."
        ),
        "",
        "\\input{tables/table_sensitivity_worst_groups}",
        "\\input{tables/table_sensitivity_coverage}",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path


def _history_speedup(summary: AblationSummary) -> float:
    history_rows = [row for row in summary.rows if row.predictor == "history"]
    if not history_rows:
        return 0.0
    return max(row.mean_speedup for row in history_rows)


def _best_config_text(row: AblationRow | ChainScalingRow | DimensionScalingRow) -> str:
    predictor = _escape_latex(row.predictor)
    if isinstance(row, ChainScalingRow):
        return f"{predictor}, {row.num_chains} chains, bucket size {row.bucket_size}"
    if isinstance(row, DimensionScalingRow):
        return f"{predictor}, D={row.dimension}, bucket size {row.bucket_size}"
    return f"{predictor}, bucket size {row.bucket_size}"


def _escape_latex(value: str) -> str:
    return (
        value.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("$", "\\$")
        .replace("#", "\\#")
        .replace("_", "\\_")
        .replace("{", "\\{")
        .replace("}", "\\}")
    )


def _format_bucket_size(bucket_size: int) -> str:
    if bucket_size == 0:
        return "--"
    return str(bucket_size)


def _format_float(value: float, digits: int) -> str:
    if value != value:
        return "--"
    return f"{value:.{digits}f}"


def _format_optional_float(value: float | None, digits: int) -> str:
    if value is None:
        return "--"
    return _format_float(value, digits)
